### ISSUE TITLE
Function execution took ****** ms, finished with status: 'connection error' 

### ISSUE THREAD

**Issue by ethanfox** [firebase/snippets-node#13]
This code gives me this error:

Function execution took 11879 ms, finished with status: 'connection error' 

How can I fix this?

**Code:**

    exports.businessUpdated = functions.firestore.document('businesses/{uid}').onCreate(event => {
    // Get the note document
    const note = event.data.data();

    // Add an 'objectID' field which Algolia requires
    note.objectID = event.params.noteId;

    // Write to the algolia index
    const index = client.initIndex(ALGOLIA_INDEX_NAME);
    return index.saveObject(note);
    
     });

**Comment by aryayudha** [comment]
i got same problem, have you solved it?

**Comment by samtstern** [comment]
@aryayudha is it possible you're trying to access an external service but are still using the free plan?
