### ISSUE TITLE
Set it in env

### ISSUE THREAD

**Issue by mrgenesis** [firebase/snippets-node#205]
https://github.com/firebase/snippets-node/blob/8985ddbfeb7320108b85eb1fa8852d807d9d79de/firestore/main/index.js#L36-L44

How can I set it in .env or system environment?
e.g. 
```js
 admin.initializeApp({ 
   credential: admin.credential.cert(process.env.SERVICE_ACCOUNT_KEY) 
 });
```

**Comment by samtstern** [comment]
This guide from Twilio is a good introduction to environment variables:
https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html
