### ISSUE TITLE
array-contains not working

### ISSUE THREAD

**Issue by narimetisaigopi** [firebase/snippets-node#23]
```js
 var citiesRef = db.collection('cities');
  var westCoastCities = citiesRef.where('regions', 'array-contains',
    'west_coast');
  return westCoastCities.get()
    .then(res => {
      console.log('West Coast get: ', res);
    });
```

rising this exception
Argument "opStr" is not a valid FieldComparison. Operator must be one of "<", "<=", "==", ">", or ">="

**Comment by samtstern** [comment]
@narimetisaigopi what version of the SDK are you using?  Also is this Node or Web Javascript?

**Comment by narimetisaigopi** [comment]
node version 6.2.0

**Comment by samtstern** [comment]
@narimetisaigopi sorry about the delay, I was investigating this a bit. I think you have more than one version of the firestore node SDK on your path.

Could you try deleting your whole `node_modules` folder and reinstalling?  Also could you show me all of your firebase-related dependencies in your `package.json` file?

**Comment by narimetisaigopi** [comment]
i am using Node version 6.2.0


Thanks & regards
Sai Gopi Narimeti

**Comment by samtstern** [comment]
@narimetisaigopi did you try deleting that directory?  Also could I see your whole `package.json` folder?

**Comment by samtstern** [comment]
This issue has been open for a long time with no update since November, so closing it.  Hope you got it solved!
