### ISSUE TITLE
Error: Functions did not deploy properly

### ISSUE THREAD

**Issue by RhodesSifu** [firebase/snippets-node#237]
I am trying to deploy delete sample code given. I get the "Error: Functions did not deploy properly" error even though I followed all the steps in the ReadMe doc

**Comment by samtstern** [comment]
@RhodesSifu this repository is just for snippets, if you're having trouble deploying your functions please contact Firebase support:
https://firebase.google.com/support

When you contact them it would be best if you could provide more debugging information such as the code you're trying to deploy and more logs from the error.

**Comment by RhodesSifu** [comment]
Alright will do just that. Thanks
