### ISSUE TITLE
Importing Specific Collections

### ISSUE THREAD

**Issue by AdamSHurwitz** [firebase/snippets-node#28]
**Is it possible to import specific collections from _Cloud Storage_ if you do not define specific collections in the export _cron.yaml_ file, but rather export all collections?**

In the [sample documentation](https://firebase.google.com/docs/firestore/solutions/schedule-export#cronyaml) specific collections are named in order to export in the _cron.yaml_ file. 

    cron:
    - description: "Daily Cloud Firestore Export"
     url: /cloud-firestore-export?outputUriPrefix=gs://BUCKET_NAME[/PATH]
    target: cloud-firestore-admin
    schedule: every 24 hours

Is it feasible to export all collections, yet still import specific collections later on if needed like so.

**Example use case**

Backing up all of an app's data, and then restoring the collections for a specific user.

`gcloud alpha firestore import gs://BUCKET_NAME/USER/USER_NAME`

**Comment by samtstern** [comment]
Yes that works!  Just specify the collection ID when you import in the same
way and the import will skip the rest.
