### ISSUE TITLE
What if token has expired when delete collection?

### ISSUE THREAD

**Issue by takehilo** [firebase/snippets-node#29]
This question is about the deleting collections and subcollections solution ([Doc](https://firebase.google.com/docs/firestore/solutions/delete-collections)).

As the document describes, our function should get `token` from environment variables and pass it to the delete function, but the `token` would expire and the request would fail.
Any advice on how to keep the `token` valid?

Thank you.

**Comment by samtstern** [comment]
@takehilo good question!  The tokens produced by `firebase login:ci` are refresh tokens so they live forever unless you explicitly revoke them.  So you can store them in your environment one time and then expect them to keep working with no effort.

**Comment by takehilo** [comment]
My mistake was to use `access_token` generated by `login` instead of `token` generated by `login:ci`.
Thank you for your quick reply!
