### ISSUE TITLE
snap.data is not a function

### ISSUE THREAD

**Issue by iwikal** [firebase/snippets-node#31]
https://github.com/firebase/snippets-node/blob/3c6333a39b91eaca2a265b725675451220e25229/firestore/extend-with-functions/functions/index.js#L20

When I emulate an `onCreate` function in the firestore shell, it tells me `snap.data` isn't a function. When I log `snap` it seems to be an instance of `DataSnapshot`, which has no data method according to [the documentation](https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot), but it does have a `val` method, which returns what I want.

**Comment by samtstern** [comment]
@iwikal I think there may be some confusion here.  The `DataSnapshot` class you linked is from the Realtime Database, but the `snap.data()` line of code you're showing comes from a function triggered by Cloud Firestore.

The `data()` method is defined here:
https://firebase.google.com/docs/reference/functions/functions.firestore.DocumentSnapshot#data

**Comment by iwikal** [comment]
Oh, sorry! And thanks!
