### ISSUE TITLE
Not possible to run a recursive delete function using 'firebase-tools' like in the suggested solution

### ISSUE THREAD

**Issue by Hibrix-net** [firebase/snippets-node#341]
Hi,

It is not possible to deploy a cloud function running a similar code as here: https://github.com/firebase/snippets-node/tree/master/firestore/solution-deletes

Whenever the 'firebase-tools' package is required from the cloud functions context the following error is thrown during the deployment:
`Error: ENOENT: no such file or directory, mkdir '/www-data-home/.config/configstore'`

However, if testing locally with the firebase function emulator the same code works without problems.

Could you please help me deploy my code?

Kind regards,

**Comment by Hibrix-net** [comment]
As an update: A Google engineer suggested me to downgrade the Node engine for functions to v 16 instead of 18 so by now everything works well but still a correction/upgrade is needed. Is anybody taking care of this?

**Comment by lboatto** [comment]
I got the same error trying to deploy any cloud functions using Node.js 18.

Using Node.js 16 fixed the problem.

**Comment by jasonc624** [comment]
"firebase-tools": "^11.18.0", and Node 16 but still doesnt work for me.
