### ISSUE TITLE
Syntax highlighting not working correctly 

### ISSUE THREAD

**Issue by IvanBila** [firebase/snippets-node#47]
### Summary
As a side effect of #46, the current documentation syntax highlighting is not working as expected some parts get syntax highlighting but all that include `let` are not, I've attached the screenshot below for reference.

### Preview
![Screenshot from 2019-06-09 14-57-19](https://user-images.githubusercontent.com/13482373/59159257-27101080-8ac7-11e9-82c0-a605fb9e4766.png)

**Comment by samtstern** [comment]
Thanks @IvanBila it looks like our syntax highlighter is not ready for modern JavaScript, I will follow up with the documentation team and see if we can update it.  Hopefully it's not a hard change to make.

**Comment by samtstern** [comment]
> Hopefully it's not a hard change to make.

Well turns out it's an *extremely* hard change to make because of silly internal Google things.  But I am working on it.

**Comment by IvanBila** [comment]
@samtstern Is it possible to maybe revert the commit that uses `let` until this issue is fixed? `let` me know what is your opinion.

**Comment by samtstern** [comment]
@IvanBila I think I'd prefer the nicer code over the nicer colors

**Comment by IvanBila** [comment]
@samtstern I also agree on that, talking about nice code, (OFF TOPIC)I wanted to add `async/await` as an extra part of the docs(maybe at the bottom), where I just show how to do the same `thing using async await`. What is your opinion on this?

**Comment by thatfiredev** [comment]
@IvanBila looks like all instances of `let` have been replaced with `const` and `async/await` has been added in #121 
Closing this now
