### ISSUE TITLE
Scheduled backup needs to be updated to Node10

### ISSUE THREAD

**Issue by ghowen** [firebase/snippets-node#57]
Node.js 8 support for the App Engine Standard environment is being deprecated, requiring you to upgrade your App Engine Standard applications to Node.js 10 by October 1, 2019. After said date, you will be unable to deploy Node.js 8 versions to your applications.

**Comment by samtstern** [comment]
@ghowen thanks!  You're right, we need to do this.

**Comment by samtstern** [comment]
also #56 will address this by moving to Cloud Functions

**Comment by ghowen** [comment]
@samtstern Thanks. Actually package.json needs to be updated as well as the engine still points to node 8.
