### ISSUE TITLE
Incorrect Comment?

### ISSUE THREAD

**Issue by RSchneyer** [firebase/snippets-node#7]
https://github.com/firebase/snippets-node/blob/5867388bdbb2ba202bfa4f0d926ea31b6bdd3500/firestore/main/index.js#L162-L169

The comment says that the code creates a document with the name 'DC', but the path is for a document with the name 'LA'. I believe the comment should say 'LA'. 

Sorry if this has already been noticed, I'm still new to this.

**Comment by samtstern** [comment]
@RSchneyer thanks for noticing, fixed!
