### ISSUE TITLE
Can not push branch after following contributor instructions

### ISSUE THREAD

**Issue by aaronhong** [firebase/snippets-node#92]
After following the [instructions for submitting a pull request](https://github.com/firebase/snippets-node/blob/master/CONTRIBUTING.md#submitting-a-pull-request) and signing the CLA I still can not push my branch to `origin`.

```
 $ git push origin clean-up-delete-collection-example
ERROR: Permission to firebase/snippets-node.git denied to {username}.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by samtstern** [comment]
@aaronhong whoops it looks like those instructions are not correct!  You'll need to push your branch to your own fork of this repo and then start the Pull Request.  Let me know if you need help doing that, I will update the `CONTRIBUTING` file.

**Comment by aaronhong** [comment]
Thanks for updating. Works with the fork.
